name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snk

      - name: Generate snake
        run: |
          snk --username yashmish18 --output output/github-contribution-grid-snake-dark.svg

      - name: Push to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/github-contribution-grid-snake-dark.svg
          git commit -m "Update snake animation" || exit 0
          git push 